// Package merge combines several gitignore templates into one file.
//
// Templates are emitted in the order the user asked for them, each under a
// header naming its source. A pattern that already appeared in an earlier
// block is dropped; when that empties out a paragraph, its comments go too,
// so the result has no headings left explaining rules that aren't there.
package merge

import (
	"strings"
)

// Block is one named template to include in the output.
type Block struct {
	// Name identifies the source in the emitted header, e.g. "Go".
	Name string
	// Content is the raw template text.
	Content string
}

// Preamble is the comment written at the top of every generated file.
const Preamble = "# Generated by igo"

// Merge renders blocks into a single .gitignore. The result always ends
// with exactly one newline.
func Merge(blocks []Block) string {
	var out strings.Builder

	out.WriteString(Preamble + "\n")
	if names := blockNames(blocks); names != "" {
		out.WriteString("# Templates: " + names + "\n")
	}

	seen := make(map[string]bool)
	for _, block := range blocks {
		body := dedupe(block.Content, seen)
		out.WriteString("\n# --- " + block.Name + " ---\n")
		if body == "" {
			// The header stays so the file still reflects what was asked
			// for, but a bare one would look like a mistake.
			body = "# (every pattern is already covered above)"
		}
		out.WriteString(body)
		out.WriteString("\n")
	}
	return out.String()
}

func blockNames(blocks []Block) string {
	names := make([]string, len(blocks))
	for i, b := range blocks {
		names[i] = b.Name
	}
	return strings.Join(names, ", ")
}

// paragraph is a run of non-blank lines plus the blank lines that preceded
// it, which is how blank-line structure survives the rewrite.
type paragraph struct {
	lead  int
	lines []string
}

// dedupe drops pattern lines already present in seen, records the ones it
// keeps, and discards any paragraph left with no patterns at all.
func dedupe(content string, seen map[string]bool) string {
	var kept []paragraph
	for _, para := range paragraphs(content) {
		var lines []string
		patterns, survivors := 0, 0
		for _, line := range para.lines {
			if isComment(line) {
				lines = append(lines, line)
				continue
			}
			patterns++
			key := strings.TrimSpace(line)
			if seen[key] {
				continue
			}
			seen[key] = true
			survivors++
			lines = append(lines, line)
		}
		// A paragraph that was all comments is a standalone note and stays.
		// One that had patterns is only worth keeping if some survived.
		if patterns > 0 && survivors == 0 {
			continue
		}
		kept = append(kept, paragraph{lead: para.lead, lines: lines})
	}

	var out strings.Builder
	for i, para := range kept {
		if i > 0 {
			// One newline ends the previous paragraph, the rest are the
			// blank lines that separated the two in the source.
			out.WriteString(strings.Repeat("\n", max(para.lead, 1)+1))
		}
		out.WriteString(strings.Join(para.lines, "\n"))
	}
	return out.String()
}

// paragraphs splits content on blank lines, remembering how many blank
// lines preceded each one.
func paragraphs(content string) []paragraph {
	var paras []paragraph
	current := -1
	blanks := 0

	for line := range strings.Lines(content) {
		line = strings.TrimRight(line, "\r\n")
		if strings.TrimSpace(line) == "" {
			blanks++
			current = -1
			continue
		}
		if current < 0 {
			paras = append(paras, paragraph{lead: blanks})
			current = len(paras) - 1
			blanks = 0
		}
		paras[current].lines = append(paras[current].lines, line)
	}
	return paras
}

func isComment(line string) bool {
	return strings.HasPrefix(strings.TrimLeft(line, " \t"), "#")
}
