package merge

import (
	"strings"
	"testing"
)

func TestMerge(t *testing.T) {
	tests := []struct {
		name   string
		blocks []Block
		want   string
	}{
		{
			name:   "single block keeps its blank-line structure",
			blocks: []Block{{Name: "Go", Content: "# bin\n*.exe\n\n# test\n*.test\n"}},
			want: `# Generated by igo
# Templates: Go

# --- Go ---
# bin
*.exe

# test
*.test
`,
		},
		{
			name: "duplicate patterns are dropped from later blocks",
			blocks: []Block{
				{Name: "A", Content: "*.log\n*.tmp\n"},
				{Name: "B", Content: "*.tmp\n*.bak\n"},
			},
			want: `# Generated by igo
# Templates: A, B

# --- A ---
*.log
*.tmp

# --- B ---
*.bak
`,
		},
		{
			name: "a paragraph loses its comment when every pattern is a duplicate",
			blocks: []Block{
				{Name: "A", Content: "# editors\n*.swp\n"},
				{Name: "B", Content: "# editors\n*.swp\n\n# build\nbuild/\n"},
			},
			want: `# Generated by igo
# Templates: A, B

# --- A ---
# editors
*.swp

# --- B ---
# build
build/
`,
		},
		{
			name: "a fully covered block keeps its header and says so",
			blocks: []Block{
				{Name: "A", Content: "*.log\n"},
				{Name: "B", Content: "*.log\n"},
			},
			want: `# Generated by igo
# Templates: A, B

# --- A ---
*.log

# --- B ---
# (every pattern is already covered above)
`,
		},
		{
			name:   "comment-only paragraphs are kept",
			blocks: []Block{{Name: "A", Content: "# just a note\n\n*.log\n"}},
			want: `# Generated by igo
# Templates: A

# --- A ---
# just a note

*.log
`,
		},
		{
			name:   "repeated blank lines between paragraphs survive",
			blocks: []Block{{Name: "A", Content: "a\n\n\n\nb\n"}},
			want: `# Generated by igo
# Templates: A

# --- A ---
a



b
`,
		},
		{
			name:   "leading and trailing blank lines are trimmed",
			blocks: []Block{{Name: "A", Content: "\n\n*.log\n\n\n"}},
			want: `# Generated by igo
# Templates: A

# --- A ---
*.log
`,
		},
		{
			name:   "CRLF input produces LF output",
			blocks: []Block{{Name: "A", Content: "*.log\r\n\r\n*.tmp\r\n"}},
			want: `# Generated by igo
# Templates: A

# --- A ---
*.log

*.tmp
`,
		},
		{
			name:   "content without a trailing newline still ends with one",
			blocks: []Block{{Name: "A", Content: "*.log"}},
			want: `# Generated by igo
# Templates: A

# --- A ---
*.log
`,
		},
		{
			name:   "an empty template is reported rather than left blank",
			blocks: []Block{{Name: "A", Content: ""}},
			want: `# Generated by igo
# Templates: A

# --- A ---
# (every pattern is already covered above)
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := Merge(tt.blocks)
			if got != tt.want {
				t.Errorf("Merge() mismatch\n--- got ---\n%s\n--- want ---\n%s", got, tt.want)
			}
		})
	}
}

// A pattern that only differs by surrounding whitespace is the same
// pattern, but the first spelling is what gets written out.
func TestMergeDedupeIgnoresSurroundingSpace(t *testing.T) {
	got := Merge([]Block{
		{Name: "A", Content: "*.log\n"},
		{Name: "B", Content: "  *.log  \n*.tmp\n"},
	})
	if strings.Count(got, "*.log") != 1 {
		t.Errorf("expected *.log once, got:\n%s", got)
	}
	if !strings.Contains(got, "*.tmp") {
		t.Errorf("expected *.tmp to survive, got:\n%s", got)
	}
}

func TestMergePreservesInterCharacterCarriageReturn(t *testing.T) {
	// The macOS template really does contain Icon[\r], a character class
	// holding a carriage return. Trimming line endings must not touch it.
	got := Merge([]Block{{Name: "macOS", Content: "Icon[\r]\n"}})
	if !strings.Contains(got, "Icon[\r]") {
		t.Errorf("carriage return inside the line was lost:\n%q", got)
	}
}

func TestMergeNoBlocks(t *testing.T) {
	got := Merge(nil)
	if got != Preamble+"\n" {
		t.Errorf("got %q, want %q", got, Preamble+"\n")
	}
}
